# fly.toml app configuration file generated for eventhandlerephemeriia on 2024-08-11T03:32:46+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'eventhandlerephemeriia'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory_mb = 512

[mounts]
source="log_volume"
destination="/logs"
